default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: brayangt_dev


test:
  <<: *default
  database: brayangt_test


production:
  <<: *default
  database: brayangt_prod
  username: brayangt
  password: <%= ENV['BRAYANGT_DATABASE_PASSWORD'] %>
